apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pr-manifest
spec:
  description: This task creates a branch for a PR to point to the image tag created
    with the short commit.
  params:
  - description: Used to tag the built image.
    name: image
    type: string
  - default: main
    description: Target branch to push to
    name: target-branch
    type: string
  - default: Tekton Pipeline
    description: Git user name for performing the push operation.
    name: git_user_name
    type: string
  - default: tekton@tekton.com
    description: Git user email for performing the push operation.
    name: git_user_email
    type: string
  - description: File in which the image configuration is stored.
    name: configuration_file
    type: string
  - description: Repo in which the image configuration is stored.
    name: repository
    type: string
  steps:
  - image: alpine/git:latest
    name: git
    script: |-
      # Setting up the git config.
      git config --global user.email "$(params.git_user_email)"
      git config --global user.name "$(params.git_user_name)"

      # Checkout target branch to avoid the detached HEAD state
      TMPDIR=$(mktemp -d)

      cd $TMPDIR
      git clone $(params.repository)
      cd securing-software-supply-chain
      git checkout -b $(params.target-branch)

      # Set to the short commit value passed as parameter.
      # Notice the enclosing " to keep it as a string in the resulting YAML.
      IMAGE=\"$(params.image)\"

      sed -i "s#\(.*value:\s*\).*#\1 ${IMAGE}#" $(params.configuration_file)

      git add $(params.configuration_file)
      git commit -m "Automatically updated manifest to point to image tag $IMAGE"
      git push origin $(params.target-branch)
