apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: scan-code
spec:
  params:
  - default: docker.io/sonarsource/sonar-scanner-cli:latest
    name: scanImage
    type: string
  - default: https://sonarqube-sonarqube.apps.cluster-tpn6s.sandbox2653.opentlc.com/
    name: sonarqubeHostUrl
    type: string
  - default: object-detection-rest
    name: sonarqubeProjectKey
    type: string
  - default: object-detection-rest-sonarqube-secret
    name: sonarqubeProjectSecret
    type: string
  - default: "true"
    name: verbose
    type: string
  steps:
  - env:
    - name: SONAR_TOKEN_WEB_UI
      valueFrom:
        secretKeyRef:
          key: token
          name: $(params.sonarqubeProjectSecret)
    image: $(params.scanImage)
    name: scan-code
    script: |
      set -x
      echo $(ls -a)
      sonar-scanner -X -Dsonar.projectKey=$(params.sonarqubeProjectKey) -Dsonar.sources=./ -Dsonar.host.url=$(params.sonarqubeHostUrl) -Dsonar.login=$SONAR_TOKEN_WEB_UI
    workingDir: /workspace/repository
  workspaces:
  - name: repository
