apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: app-globex-ui-template
spec:
  params:
  - description: The git branch for this PR.
    name: io.openshift.build.commit.ref
  - description: the specific commit SHA.
    name: io.openshift.build.commit.id
  - description: The date at which the commit was made
    name: io.openshift.build.commit.date
  - description: The name of the github user handle that made the commit
    name: io.openshift.build.commit.author
  - description: The commit message
    name: io.openshift.build.commit.message
  - description: The host name of the git repo
    name: gitRepoHost
  - description: The git repository URL.
    name: gitrepositoryurl
  - description: The repository name for this PullRequest.
    name: fullname
  - description: The repository to push built images to.
    name: imageRepoDev
  - description: The repository to push built images to.
    name: imageRepoProd
  - description: The file to update to point to newly built image
    name: manifestFile
  - description: The file to update to point to newly built image in prod
    name: manifestFileProd
  - description: The repo to update to point to newly built image
    name: manifestRepo
  - description: The full name of the repo
    name: manifestRepoName
  - description: Enable image repository TLS certification verification.
    name: tlsVerify
  - description: Extra parameters passed for the push command when pushing images.
    name: build_extra_args
  - description: Target image repository name
    name: imageRepo
  - description: Sonarqube host url
    name: sonarqubeHostUrl
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: app-globex-ui-pipeline-
    spec:
      params:
      - name: REPO_HOST
        value: $(tt.params.gitRepoHost)
      - name: GIT_REPO
        value: $(tt.params.gitrepositoryurl)
      - name: TLSVERIFY
        value: $(tt.params.tlsVerify)
      - name: BUILD_EXTRA_ARGS
        value: $(tt.params.build_extra_args)
      - name: IMAGE_REPO
        value: $(tt.params.imageRepo)
      - name: IMAGE_TAG
        value: $(tt.params.io.openshift.build.commit.ref)-$(tt.params.io.openshift.build.commit.id)
      - name: MANIFEST_FILE
        value: $(tt.params.manifestFile)
      - name: MANIFEST_FILE_PROD
        value: $(tt.params.manifestFileProd)
      - name: MANIFEST_REPO
        value: $(tt.params.manifestRepo)
      - name: MANIFEST_REPO_NAME
        value: $(tt.params.manifestRepoName)
      - name: COMMIT_SHA
        value: $(tt.params.io.openshift.build.commit.id)
      - name: GIT_REF
        value: $(tt.params.io.openshift.build.commit.ref)
      - name: COMMIT_DATE
        value: $(tt.params.io.openshift.build.commit.date)
      - name: COMMIT_AUTHOR
        value: $(tt.params.io.openshift.build.commit.author)
      - name: COMMIT_MESSAGE
        value: $(tt.params.io.openshift.build.commit.message)
      - name: SONARQUBE_HOST_URL
        value: $(tt.params.sonarqubeHostUrl)
      - name: SONARQUBE_PROJECT_KEY
        value: globex-ui
      - name: SONARQUBE_PROJECT_SECRET
        value: globex-ui-sonarqube-secret
      pipelineRef:
        name: app-globex-ui-pipeline
      serviceAccountName: pipeline
      workspaces:
        - name: shared-data
          volumeClaimTemplate:
            metadata:
              creationTimestamp: null
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 3Gi
            status: {}
        - emptyDir: {}
          name: maven-settings
        - emptyDir: {}
          name: signature
        - name: secrets
          secret:
            secretName: gpg-public-key